name: Proxy.py Library

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    name: Library - Python ${{ matrix.python }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}-dev
      - run: pip install -r requirements.txt
      - run: pip install -r requirements-testing.txt
      - name: Quality Check
        run: |
          flake8 --ignore=W504 --max-line-length=127 proxy/ tests/ setup.py
          mypy --strict --ignore-missing-imports proxy/ tests/ setup.py
      - name: Run Tests
        run: pytest --cov=proxy tests/
      - name: Upload coverage to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: codecov
